apiVersion: v1
kind: Service
metadata:
  name: svnrepo-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
    protocol: TCP
  selector:
    app: svnrepo
---
kind: Deployment
metadata:
  name: svnrepo
spec:
 template:
  metadata:
      labels:
        app: svnrepo
  spec:
    containers:
    - name: svnrepo
      image: app1gstasoa023e.pre.sicredi.net:5000/docker.wso2.com/svnrepo
      ports:
        - containerPort: 80
