apiVersion: v1
kind: Service
metadata:
  name: wso2am-store
spec:
  type: NodePort
  ports:
  - port: 9443
    nodePort: 31448
    targetPort: 9443
    protocol: TCP
    name: defaultport
  - port: 4000
    targetPort: 4000
    name: cluster
  selector:
    app: wso2am-store
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2am-store
spec:
 template:
  metadata:
      labels:
        app: wso2am-store
  spec:
    containers:
    - name: wso2am-store
      image: app1gstasoa023e.pre.sicredi.net:5000/wso2am-store-sicredi:2.0.0 
      env:
        - name: ANALYTICS_REST_URL
          value: https://wso2am-analytics.default.svc.cluster.local:9444
        - name: ANALYTICS_REST_USER
          value: admin
        - name: ANALYTICS_REST_PWD
          value: admin
        - name: ANALYTICS_URL
          value: tcp://wso2am-analytics.default.svc.cluster.local:7612
        - name: ANALYTICS_SSL_URL
          value: ssl://wso2am-analytics.default.svc.cluster.local:7712
        - name: ANALYTICS_USER
          value: admin
        - name: ANALYTICS_PWD
          value: admin
        - name: MY_URL_STATDB
          value: jdbc:mysql://wso2db-service.default.svc.cluster.local:3306/stats_db?autoReconnect=true\&amp;relaxAutoCommit=true
        - name: MY_URL_APIDB
          value: jdbc:mysql://wso2db-service.default.svc.cluster.local:3306/apimgtdb?autoReconnect=true
        - name: MY_URL_USERSDB
          value: jdbc:mysql://wso2db-service.default.svc.cluster.local:3306/userdb?autoReconnect=true
        - name: MY_URL_REGDB
          value: jdbc:mysql://wso2db-service.default.svc.cluster.local:3306/regdb?autoReconnect=true
        - name: MY_JDBCDRIVER
          value: com.mysql.jdbc.Driver
        - name: MY_USER
          value: root
        - name: MY_PWD
          value: root
        - name: SVN_REPO_URL
          value: http://svnrepo-service.default.svc.cluster.local/repos/
        - name: SVN_REPO_USER
          value: user 
        - name: SVN_REPO_PWD
          value: password
        - name: KM_URL
          value: https://wso2am-key.default.svc.cluster.local:9443/services/
        - name: GW_MANAGER_URL
          value: https://wso2am-gwmanager.default.svc.cluster.local:9443/services
        - name: GW_ENDPOINT
          value: http://wso2am-gwworker.default.svc.cluster.local:8280,https://wso2am-gwworker.default.svc.cluster.local:8243
        - name: GW_REVOKE_URL
          value: https://wso2am-gwworker.default.svc.cluster.local:8243/revoke
      ports:
        - containerPort: 9443
          name: defaultport
        - containerPort: 4000
          name: cluster
