apiVersion: v1
kind: Service
metadata:
  name: wso2db-service
spec:
  type: NodePort
  ports:
  - port: 3306 
    nodePort: 31114
    targetPort: 3306
    protocol: TCP
  selector:
    app: wso2db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2db 
spec:
 template:
  metadata:
      labels:
        app: wso2db
  spec:
    containers:
    - name: mysql
      image: app1gstasoa023e.pre.sicredi.net:5000/wso2am-db-sicredi
      env:
        - name: MYSQL_ROOT_PASSWORD 
          value: root
      ports:
        - containerPort: 3306
